# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml
trigger:
  tags:
    include:
    - release/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      archiveName: 'unison-linux64'
    mac:
      imageName: 'macos-10.13'
      archiveName: 'unison-osx'
#    windows:
#      imageName: 'vs2017-win2016'
#      archiveName: 'unison-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: curl -sSL https://get.haskellstack.org/ | sh
  displayName: 'Install stack'

- script: |
    echo Build.ArtifactStagingDirectory = $(Build.ArtifactStagingDirectory)
    echo System.DefaultWorkingDirectory = $(System.DefaultWorkingDirectory)
    pwd
    export PATH=$HOME/.local/bin:$PATH
    export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
    git submodule init
    git submodule update
    stack query
    stack build
    cp .stack-work/install/*/*/*/bin/unison ucm

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/archive-files?view=azure-devops
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/ucm'
    archiveType: 'tar'
    tarCompression: 'gz'
    includeRootFolder: false

# GitHub Release
# Create, edit, or delete a GitHub release
- task: GitHubRelease@0
  inputs:
    gitHubConnection: aryairani2
    assets: '$(Build.ArtifactStagingDirectory)/ucm'
